name: DEPLOY

on:
  push:
    branches:
      - 'releases/**'
    tags-ignore:
      - '*.*'

env:
  NO_HEADLESS_TEST: true
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat --no-daemon
        shell: cmd
      - run: CALL gradlew.bat --no-daemon assemble check publishMingwX64PublicationToMavenRepository -x jsBrowserTest -x jsNodeTest
        shell: cmd

  publish-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew --no-daemon
      - run: ./gradlew --no-daemon  assemble check publish -x publishKotlinMultiplatformPublicationToMavenRepository -x jsBrowserTest -x jsNodeTest

  publish-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon  assemble check lint testDebugUnitTest publishKotlinMultiplatformPublicationToMavenRepository publishLinuxX64PublicationToMavenRepository -x jsBrowserTest -x jsNodeTest

  publish-finalize:
    needs: [publish-windows, publish-mac, publish-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew actuallyPublishBintray
